# Generated by Django 3.0.7 on 2020-12-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=230)),
                ('phone', models.CharField(max_length=12)),
                ('msg', models.TextField()),
            ],
        ),
    ]
